[package]
name = "door"
version = "0.1.0"
authors = ["baiyan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core={path="core"}
resource = "0.2.1"

[workspace]
members = [
    "core",
    "tester"
]